### ISSUE TITLE
File in-memory store (mostly for vocabs)

### ISSUE THREAD

**Issue by l00mi** [zazuko/trifid-handler-fs#1]
- one or multiple .ttl files are merge into one in-memory store (rdf-ext slang)
- the store implements a simple match query which delivers the resource back

**Comment by l00mi** [comment]
and extension or second handler for the same functionality but with remote vocabs like e.g.:

* http://qudt.org/2.0/schema/SCHEMA_QUDT-v2.0.ttl
* https://www.w3.org/2000/01/rdf-schema#

**Comment by l00mi** [comment]
There is not necessary a need for a SPARQL query, it should be enough to have something like for the describe:  `store.match(resource)`

**Comment by bergos** [comment]
[trifid-handler-file](https://github.com/zazuko/trifid-handler-file) implements all requested features of this issue.
